### ISSUE TITLE
getting the latest trackerslist info

### ISSUE THREAD

**Issue by minhoryang** [CorralPeltzer/newTrackon#1]
https://github.com/ngosang/trackerslist

**Comment by CorralPeltzer** [comment]
I'm sorry, what is exactly the issue?

**Comment by Phentora** [comment]
I think he wants you to implement some sort of scraper that updates the trackers on your database with what he has on his Git. AFAIK he has a script that checks the trackers on his list every X hours and if a tracker is not responding it gets deleted.
