### ISSUE TITLE
cant run it 

### ISSUE THREAD

**Issue by Allesanddro** [CorralPeltzer/newTrackon#10]
`root@ubuntu:/var/www/html/track# python3 server.py
Traceback (most recent call last):
  File "server.py", line 4, in <module>
    from bottle import Bottle, run, static_file, request, response, HTTPError, redirect, mako_template as template
ImportError: No module named 'bottle'
`

` pip install -r requirements.txt
Requirement already satisfied: bottle==0.12.13 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 1))
Requirement already satisfied: dnspython==1.15.0 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 2))
Requirement already satisfied: Mako==1.0.6 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 3))
Requirement already satisfied: requests==2.14.2 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 4))
Requirement already satisfied: waitress==1.0.2 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 5))
Requirement already satisfied: wsgi-request-logger==0.4.6 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 6))
Requirement already satisfied: MarkupSafe>=0.9.2 in /usr/local/lib/python2.7/dist-packages (from Mako==1.0.6->-r requirements.txt (line 3))
`

system ubuntu 16.10

**Comment by Allesanddro** [comment]
im stupid maybe i should use python3-pip :c

**Comment by CorralPeltzer** [comment]
You are right, gonna update the tutorial with pip3

**Comment by Allesanddro** [comment]
<3
