### ISSUE TITLE
Automatic removal of dead trackers

### ISSUE THREAD

**Issue by AnimMouse** [CorralPeltzer/newTrackon#101]
Suggestion: Trackers that have 0% uptime (this may not be fair according to the [FAQ](https://newtrackon.com/faq)) and those trackers that "Can't resolve IP" should be deleted from the list.

**Comment by CorralPeltzer** [comment]
Thanks! I think removing them just by reaching 0% or not resolving to an IP is just too premature. Some trackers go down for a few months and then they come back.

I usually remove trackers from the list that have been dead for more than 2 years, but it's a good idea to automate this removal.

**Comment by AnimMouse** [comment]
Yep, relying on just 1 characteristic is too premature, would rather use 2 or more other characteristics, like if the tracker is dead for 1 year or 2 years or more.

Looking forward for automation of removal of dead trackers.

**Comment by AnimMouse** [comment]
Nice.
