### ISSUE TITLE
Handling of duplicate IPs on HTTP/HTTPS trackers

### ISSUE THREAD

**Issue by AnimMouse** [CorralPeltzer/newTrackon#102]
Suggestion: HTTP/HTTPS Trackers that use Cloudflare basically resolves to the same IP address and also trackers that use virtual hosts as stated in the [HTTP/1.1](https://www.w3.org/Protocols/rfc2616/rfc2616.html) specification (that allows many websites/trackers on the same IP) also have the same IP address. HTTP/HTTPS trackers should be exempted from that rule.

**Comment by CorralPeltzer** [comment]
Thanks for the suggestion!

However, this would allow anyone to submit an infinite amount of subdomains to newTrackon. (http://1.tracker.com/announce, http://2.tracker.com/announce, http://3.tracker.com/announce...) just by creating a wildcard DNS record (*.tracker.com)

The limits on duplicate trackers are not only to avoid spamming, but also about decentralization, both of domain and ISPs (AS). Having lots of trackers hosted in the same IP/ISP/domain is the kind of centralization that BitTorrent tries to avoid, and makes them vulnerable to a single takedown request. If I were to treat Cloudflare IPs differently, it would be by banning their IP ranges. Having all trackers behind Cloudflare would mean a single organization being able to monitor and take down all of them.

I think the current solution is a good compromise, but I'm always open for ideas.

**Comment by AnimMouse** [comment]
Thanks for the answer!

Yep, someone can spam newTrackon just like that, (IMO who the f someone will spam like that, hahahaha!) But for sure running the same tracker instance on multiple domains will send the same response, and detecting them as duplicate.

True, having the same IP makes them vulnerable to a single takedown request but in the day of IPv4 exhaustion (I really like that newTrackon prioritizes IPv6) there are people runs trackers on the same IP because IPv4 is really expensive now and if I were to avoid centralization, I would ditch this tracker stuff already and go full DHT.

**Comment by CorralPeltzer** [comment]
DHT is in general a better technology for peer discovery, but BitTorrent trackers can be faster or work in situations where DHT doesn't work due to network limitations.

**Comment by AnimMouse** [comment]
Ok, no worries.
