### ISSUE TITLE
BEP 34: respecting DNS TXT record of tracker (DNS Tracker Preferences)

### ISSUE THREAD

**Issue by AnimMouse** [CorralPeltzer/newTrackon#103]
Suggestion: Let newTrackon query for TXT record for "BITTORRENT" according to [BEP 34](http://bittorrent.org/beps/bep_0034.html)

If "BITTORRENT DENY ALL" was found, delete the tracker on trackerlist.

If tracker uses UDP:X and/or TCP:X. Let newTrackon list what the server preferred to use.

**Comment by txtsd** [comment]
What's the holdup on this?

**Comment by AnimMouse** [comment]
It seems like newTrackon is not deleting trackers when `BITTORRENT DENY ALL` is found, only saying `Tracker denied connection according to BEP34` in the Raw Data and stops connection.
And using `BITTORRENT TCP:X` changes the protocol into UDP instead of HTTPS.

**Comment by CorralPeltzer** [comment]
@AnimMouse thanks for catching that! I've just fixed those 2 issues.
