### ISSUE TITLE
udp/http(s) on different port not work?

### ISSUE THREAD

**Issue by GongT** [CorralPeltzer/newTrackon#108]
I have add https url, there are two items in "Submitted" list:
![image](https://user-images.githubusercontent.com/2265048/86973576-65cf3900-c1a7-11ea-9f77-7db7b5cfc998.png)

But my udp server is on port `43079`, not same with https, is this can't be done now?

(submit another one do not work)

**Comment by CorralPeltzer** [comment]
Hi! When a tracker is accepted with a specific protocol and port, that's what stays in the list. All other submissions of the same domain will count as duplicates.

I have manually removed the https tracker and submitted the udp version, please let me know if you wanted something else.
