### ISSUE TITLE
Why do we reject trackers with an interval <5min and >3h?

### ISSUE THREAD

**Issue by txtsd** [CorralPeltzer/newTrackon#120]
What is the reasoning behind this?

For interval <5min, we can just announce every hour or so, and for interval >3h we can announce at whatever the interval time is.

**Comment by AnimMouse** [comment]
Some people that provide torrent tracker can't afford the bandwidth with the interval time of 3 hours, let alone 5 mins. They should also be included on this list.

**Comment by CorralPeltzer** [comment]
Hi! Thanks for the feedback.

First of all, I think you'll agree there needs to be an upper limit. For example, a tracker with 1000 hours of interval (41+ days) would not be useful, and newTrackon could not properly calculate its uptime. Most peers will be retrieved via Peer Exchange after the first announce request anyways. As for the bandwidth argument, I'd say if someone is bandwidth limited, they probably should not run a public open BitTorrent tracker that can eventually get millions of requests a day. In general, the higher the interval, the lower the accuracy newTrackon can provide about the uptime of a tracker. Considering this, I think a good upper limit is 3h.

As for the lower limit, I consider a tracker with a too small interval possibly malicious. Causing BitTorrent clients to make requests really often could allow an actor to gather significant traffic, which could then be pointed at another IP. I also doubt the usefulness of this high announce frequency, peer swarms don't change so fast. I'd even consider raising this minimum interval to 10 or 15 minutes.

I'm always open to feedback and new arguments, of course.

**Comment by txtsd** [comment]
Thanks for the explanation.

We could default to setting a minimum internal of 15 minutes and a maximum of 3 hours. No need to outright reject the trackers.
