### ISSUE TITLE
REQ: don't cut announce links

### ISSUE THREAD

**Issue by Corsten56** [CorralPeltzer/newTrackon#123]
Hello.

I've a request. When adding new announce URLs newtrackon cuts its URL.

For example, add this and check:

> http://korsar.xyz/tracker/announce.php
> 
> http://korsar.tv/tracker/announce.php
> 

It is just examples, there are some more such kind announcers.

Regards.

**Comment by CorralPeltzer** [comment]
Hi! This is intentional, see reasoning in https://github.com/CorralPeltzer/newTrackon/issues/81#issuecomment-542906446.
