### ISSUE TITLE
Missing filtered list types?

### ISSUE THREAD

**Issue by user8446** [CorralPeltzer/newTrackon#127]
Hello,

If memory serves, there used to be other filtered list types instead of just the 95% uptime list. We're the other filtered lists removed intentionally?

**Comment by CorralPeltzer** [comment]
Hi! You can see all the API endpoints in https://newtrackon.com/api

Are you referring to something else?

**Comment by user8446** [comment]
Haha that wasn't there when I looked. Thanks for the project! 
Closing
