### ISSUE TITLE
[Request] allow copying list of the trackers i tested

### ISSUE THREAD

**Issue by slrslr** [CorralPeltzer/newTrackon#13]
Hello,

i added my own tracker list in aim to discover dead or bad ones and so i clean/refine my list this way. It would be good if there is a way so i can remove those that have uptime worse than certain percentage and be able to copy rest ones as a plain text (one tracker URL per line or separated by empty lines).

**Comment by CorralPeltzer** [comment]
Hi! The objective of the project is just to provide some info on trackers and a list of the most stable ones, you can get the latter on [https://newtrackon.com/list](https://newtrackon.com/list). If you want to refine the percentage of uptime, you can use the API, like [https://newtrackon.com/api/50](https://newtrackon.com/api/50) for all trackers with more than 50% uptime. I don't think returning just the trackers you submitted (your list) AND the ones already tracked by the site would bring any improvement over the current system.
