### ISSUE TITLE
request for removal/modification of trackers

### ISSUE THREAD

**Issue by jamiew0w** [CorralPeltzer/newTrackon#137]
hello!

i'm changing my setup from this:

```
udp://t1.leech.ie:1337/announce
udp://t2.leech.ie:1337/announce
udp://t3.leech.ie:1337/announce
```

to just this:

```
udp://tracker.leech.ie:1337/announce
```

is the best course of action to have all three removed and i'll resubmit the new one once online?
Thanks again for your time!

**Comment by CorralPeltzer** [comment]
Hi! Thanks for reaching out. I just removed t2 and t3, and renamed t1 to tracker.
