### ISSUE TITLE
Submissions are not showing up

### ISSUE THREAD

**Issue by txtsd** [CorralPeltzer/newTrackon#14]
I've been trying to add trackers every now and again over the past few days and most of the time submissions don't seem to be accepted. They neither show up in the queue, nor do they show up in the results when I check later on.

It isn't accepting anything right now either.

```
6:14 AM
Wednesday, September 13, 2017
Coordinated Universal Time (UTC)```

**Comment by CorralPeltzer** [comment]
Submissions seem to be working fine, but remember the instructions: 

> To make it to the queue, a tracker has to be a well-formed URL, not to be an IP, and resolve at least to an IPv4 address.

While the definition of URL is quite broad, in this case they have to be composed of the protocol, (`udp`, `http` or `https`), `://`, the domain not being an IP, and a trailing `/`. If the domain does not resolve to an IPv4 at least, it won't be added either.

`https://www.google.com/` would work, but not `www.google.com`.

These strict URL requirements are pretty bad and really need a rework, doing that soon.

**Comment by txtsd** [comment]
They were well formed. I must've been trying to add trackers that are already in the database. I should've checked first. I'll reopen this if something suspicious happens again.
