### ISSUE TITLE
API for last x responses of a known tracker

### ISSUE THREAD

**Issue by Henkyou** [CorralPeltzer/newTrackon#15]
Hello, I run one of the trackers in your list, I've noticed my uptime on your list goes down sometimes, seemingly randomly when there has been downtime on my end, and trackers in the same network experiencing no loss in uptime. Would it be possible to get an API that lists the last x number of responses from a known tracker? It'd be useful to know if there actually is any issue or if your software simply had issues connecting or experienced some unknown error.

Thanks,

Henkyou

**Comment by CorralPeltzer** [comment]
Hi! You can find the last 300 responses from all trackers in [https://newtrackon.com/raw](https://newtrackon.com/raw).

If you want to monitor just your tracker, you can set up your local instance of newTrackon, it is really easy just following the instractions in the [README](https://github.com/CorralPeltzer/newTrackon/blob/master/README.md).

If you really want to know the errors that caused your tracker not to be at 100% uptime, I keep all the logs, just tell me what is your tracker and I can send them to you.

**Comment by Henkyou** [comment]
I might try setting up my own instance, I might email you later for the logs in private.

Thank you.
