### ISSUE TITLE
Link to the IPv6-only trackers list on the site.

### ISSUE THREAD

**Issue by styromaniac** [CorralPeltzer/newTrackon#150]
.

**Comment by CorralPeltzer** [comment]
Hi! I'm not sure I understand, can you elaborate on what's the request?

**Comment by styromaniac** [comment]
Have an API link like so:

newtrackon.com/api/stable/ipv6

**Comment by CorralPeltzer** [comment]
I'm not sure what would be the usecase for this... if you have **only IPv4** connectivity, you care about trackers reachable by IPv4, and for that there's https://newtrackon.com/api/stable?include_ipv6_only_trackers=0. If you have **only IPv6** connectivity, I'd understand the need for a https://newtrackon.com/api/stable?include_ipv4_only_trackers=0 that doesn't include IPv4-only trackers.

What would be the use case to get trackers **only** reachable via IPv6?

**Comment by styromaniac** [comment]
IDK. I just thought it would be useful somehow to have IPv6 only. You may close and disregard this issue.

**Comment by Allesanddro** [comment]
I also would find this useful

**Comment by CorralPeltzer** [comment]
If you only have IPv6 connectivity, https://newtrackon.com/api/stable?include_ipv4_only_trackers=0 will return all trackers reachable by IPv6, whether they are IPv6-only, or dual-stack.

I still don't see how filtering down to IPv6-only is useful, but it's trivial to implement, so can add it as another API option.

**Comment by styromaniac** [comment]
> If you only have IPv6 connectivity, https://newtrackon.com/api/stable?include_ipv4_only_trackers=0 will return all trackers reachable by IPv6, whether they are IPv6-only, or dual-stack.
> 
> I still don't see how filtering down to IPv6-only is useful, but it's trivial to implement, so can add it as another API option.

IPv6-only trackers was a peculiar request, I admit. What I should have said is to be able to exclude IPv4-only trackers via the API.

**Comment by CorralPeltzer** [comment]
That's great, thanks for the clarification. I implemented that a couple of days ago. To achieve that, you can just invert the default selection of the 2 checkboxes in https://newtrackon.com/list, or just query https://newtrackon.com/api/stable?include_ipv4_only_trackers=0. I'll still add better API documentation as part of #154
