### ISSUE TITLE
Mass Tracker Support

### ISSUE THREAD

**Issue by Elshara** [CorralPeltzer/newTrackon#152]
Hello,
I'm half expecting this issue to be closed, and set aside, save for the fact that I am contacting you about a legitimate issue I think your site could benefit from.
Specifically, I'm referring to the "submit box" found on the home page of your site.
https://newtrackon.com/
It doesn't work (whether I add one or multiple trackers) as advertised. You can confirm this by the fact that it only refreshes a random list of 345 trackers whether you add anything in the box or not. And when checking the queue page, found here.
https://newtrackon.com/submitted
I do not see anything I submitted in the queue even after waiting 10 minutes.
The FAQ page found here.
https://newtrackon.com/faq
Says to report an issue if anything is wrong. And since, this issue started with a mysterious tracker I can't pin down. I'm looking for answers in the following ways.
What's wrong with your site? Why can't I submit multiple trackers in the queue or even a single domain?
I thought all the pages on your site, in particular, this one.
https://newtrackon.com/submitted
Worked together, with the home page to display real time or cached statistics about the trackers (likely updated via a bot or cron) regarding their status, ping time and relative IP address.
Your website was linked from a Github repository. Which I was able to find, as an off-shoot of searching for new trackers to help me complete a mysterious torrent with a peer that's online, but not responding to many popular ones...still searching to figure out which one it is.
During my travels for a tracker that shows more of them, I've been able to collect a great number of them through several means. Using Jackett, web searches and several lists found right here on Git Hub (more on this later) that they were apart of.
Granted, some of the torrent tracking URLs I have collected are featured in other Git Hub repositories. However, I would like to take this one step further. I was hoping to add my list of known trackers into your project, and see what results came back whether they're currently responding to traffic or not.
This project here.
https://github.com/ngosang/trackerslist/
As well as this one.
https://github.com/XIU2/TrackersListCollection
Mentions one another in terms of referring to each other as torrent tracker projects tracking publicly submitted UDP, IPv4, IPv6, HTTP, HTTPS and WSS trackers for peers.
They also mention your project by name, particularly the latter, in terms of waiting until you release stable trackers before they are mirrored elsewhere. The former however, accepted a few trackers from a list I gave them, which you can see here.
https://github.com/ngosang/trackerslist/issues/328
In which I came to them with information regarding new trackers that I had found through the places stated above in this issue. Though, they only added a few from the list I had. And I have since collected many more.
While the good news is, I did find the tracker that my torrent needs, I don't know what one it is that it is connecting to for peers. And so, by narrowing down active trackers, I should in theory be able to resume the download of it by weeding out the downed trackers.
Which brings me to creating this issue, hoping that somehow I'd be able to resolve this issue once and for all.
Could you please consider adding the following file to your queue for me of trackers that are working?
I hope this helps you in getting more trackers for your project. As all of them are public.
Thank you so very much.
Elshara
[Torrent Master Tracker List.txt](https://github.com/CorralPeltzer/newTrackon/files/7427560/Torrent.Master.Tracker.List.txt)

**Comment by Elshara** [comment]
Hey @txtsd I've got a question for you.
What was the character limit you came across?
In terms of New Track On specifically the remote version, I tried what you suggested, and didn't see any output change as far as submitting only domain links with /announce at the end with only two of them. No output change occurred and was taken right back to the same home screen as before.

**Comment by txtsd** [comment]
@Elshara It's 50000 characters including newlines etc.

**Comment by CorralPeltzer** [comment]
Hi! Thanks for reporting. @txtsd is right, you're hitting the 50K character limit. The file you provided has 106K characters, and submitting it in batches under the limit seems to work just fine. There needs to be a limit on bulk submission, otherwise a multi-GB list could just make the server run out of memory.

In any case, this limit can probably be increased. I'll also improve the documentation and error reporting.
