### ISSUE TITLE
Link to non-IPv6-only trackers on the site.

### ISSUE THREAD

**Issue by styromaniac** [CorralPeltzer/newTrackon#153]

**Comment by CorralPeltzer** [comment]
Hi! I'm not sure I understand, can you elaborate on what's the request?

**Comment by styromaniac** [comment]
Have an API link like so:

newtrackon.com/api/stable/ipv4

**Comment by CorralPeltzer** [comment]
The link would be https://newtrackon.com/api/stable?include_ipv6_only_trackers=0, that's what loads in https://newtrackon.com/list. In any case, I'm planning to revamp the API docs. Closing in favor of #154
