### ISSUE TITLE
Spoofing

### ISSUE THREAD

**Issue by ghost** [CorralPeltzer/newTrackon#180]
Is there any attempt to verify the accuracy of reported stats from the trackers before adding them to the list of stable trackers?

I use the main list frequently but I have to remove http://bt.okmp3.ru from my list every time, and it always come from NTO.

This tracker reports a seed for every torrent it gets, and it took me some time to "track" it down... but yeah it's a shady tracker.

Others have come up in the past but this one seems persistent.

Do you at least maintain a blacklist?  Surely you must.

I'm just letting you know my experience.

Cheers.

**Comment by txtsd** [comment]
Similar to #119 
Lists reasons for not considering a blacklist.

**Comment by destination-moon** [comment]
That's fine, but I actually stopped using NTO due to this issue. 
Cheers! 

Sent from Yahoo Mail on Android 
 
  On Mon, Jul 11, 2022 at 10:42 PM, ***@***.***> wrote:   


Similar to #119
Lists reasons for not considering a blacklist.

**Comment by lslqtz** [comment]
I think other users can maintain a blacklist list and make it public, the user can choose to use it.
You can make a program, this program can use multiple sources (list/whitelist/blacklist) to generate a list. This is a good idea.
