### ISSUE TITLE
Switch from `pipenv` to `poetry`

### ISSUE THREAD

**Issue by txtsd** [CorralPeltzer/newTrackon#210]
References:
https://peps.python.org/pep-0621/
https://packaging.python.org/en/latest/specifications/declaring-project-metadata/#declaring-project-metadata

**Comment by CorralPeltzer** [comment]
Hi! From those docs, this metadata is

> for packaging-related tools to consume

but newTrackon is not packaged as a python project, or is published to PyPI. The only supported ways to run newTrackon right now is via Docker, or by cloning the repo and installing dependencies manually.

**Comment by txtsd** [comment]
Sorry I couldn't get back to you sooner.

I understand that it isn't published to PyPI or the sort, but it helps to manage a venv for local development.

**Comment by CorralPeltzer** [comment]
I just migrated from `Pipenv` to `uv`, which included adding a `pyproject.toml` that should work fine with Poetry.
