### ISSUE TITLE
This program has an error,and I don't know how to solve it.

### ISSUE THREAD

**Issue by fooler64** [CorralPeltzer/newTrackon#221]
![屏幕截图 2023-04-21 192736](https://user-images.githubusercontent.com/106793369/233625576-53638370-db95-47a4-8670-55c4a259adfe.jpg)

**Comment by CorralPeltzer** [comment]
Hi! These type annontations were introduced in Python 3.9, so it seems you're using an older version. You can see your python version by running `python -V`
