### ISSUE TITLE
Putting Cloudflare IPs on the whitelist

### ISSUE THREAD

**Issue by WhitePr** [CorralPeltzer/newTrackon#266]
Since my Trakcer uses cloudflare for proxy, it violates the first rule in the FAQ (conflicts with other tracker IPs that use cloudflare), so I suggest whitelisting the cloudflare ip

This is my Tracker
`https://tracker.gcrreen.xyz:443/announce`

**Comment by CorralPeltzer** [comment]
Hi! The point BitTorrent, and using multiple trackers, is decentralization. Having more trackers behind Cloudflare defeats the purpose. If I were to change the policy on Cloudflare, it would be banning all its IPs.

**Comment by WhitePr** [comment]
> Hi! The point BitTorrent, and using multiple trackers, is decentralization. Having more trackers behind Cloudflare defeats the purpose. If I were to change the policy on Cloudflare, it would be banning all its IPs.

I think there is something wrong with my expression, what I want to clarify is: because of the first rule of the FAQ, when submitting a new Tracker, because of the use of Cloudflare, the resolved IP conflicts with other trackers using cloudflare and cannot be submitted. The reason I suggest whitelisting cloudflare IPs is because I've encountered this problem when submitting a tracker that uses cloudflare but can't be submitted (I can't find it in the Submitted list after submitting).

**Comment by CorralPeltzer** [comment]
Hi! I understood fine, I don't want to incentivize more trackers behind Cloudflare. I recommend moving your tracker out of Cloudflare if you want to add it to newTrackon.
