### ISSUE TITLE
ipv6 udp工作正常但是网站检测显示已经离线23天

### ISSUE THREAD

**Issue by 1265578519** [CorralPeltzer/newTrackon#278]
ipv6 udp工作正常但是网站检测显示已经离线23天

```
udp://tracker2.itzmx.com:6961/announce
```

是否处于同一/64前缀网段的原因？
![image](https://github.com/CorralPeltzer/newTrackon/assets/6442439/2cd0bbd8-9445-4dfc-8bb9-0f367c5c7589)

![image](https://github.com/CorralPeltzer/newTrackon/assets/6442439/89efb073-142d-48a1-a873-f1b4c1bfc60a)

**Comment by CorralPeltzer** [comment]
Hi! It seems this tracker works for the HTTP protocol, but not for the UDP protocol, it just times out. Whatever tool you're using might automatically fallback to HTTP if UDP fails.

See for example, in qBittorrent:

![image](https://github.com/CorralPeltzer/newTrackon/assets/6959494/ab0a21d5-50cb-46b1-8e8e-68a960858e2f)


I have changed it to HTTP for now, it shows up as working, but be aware that UDP is actually not working.

**Comment by 1265578519** [comment]
qBittorrent 默认只连接一个tracker服务器，如何设置高级选项设置连接所有的
两个选择勾上即可
![image](https://github.com/CorralPeltzer/newTrackon/assets/6442439/8a6c51d3-ece9-4214-8aff-31ba884bff3c)


如果你使用qBittorrent测试，请确保高级设置正确，可以查看你截图提供的message信息，由于你错误设置，引起响应skip

请不要更改为http，会带来更多的流量消耗，应当使用udp

udp能正常工作
![image](https://github.com/CorralPeltzer/newTrackon/assets/6442439/ef125045-79e0-44f1-864e-db39682c7e8a)

wireshark信息，都可以正常返回udp数据包
![image](https://github.com/CorralPeltzer/newTrackon/assets/6442439/4df414cd-915b-420f-80b5-47c25c694e62)

**Comment by 1265578519** [comment]
经过确认，高级设置完成后依旧提示skipping tracker announce (unreachable)
是qbittorrent不支持ipv6 tracker服务器
https://github.com/qbittorrent/qBittorrent/issues/20882
newTrackon可能借助了qb的源码实现，导致一同出现了bug

**Comment by CorralPeltzer** [comment]
Hi, I believe you're mistaken. qBittorrent works fine with IPv6 UDP trackers, my settings are the same as your screenshot, and newTrackon doesn't use any qBittorrent code, it has its own implementation. Another example to show `udp://tracker2.itzmx.com:6961/announce` is actually not responding to UDP packets is just using `udp://tracker3.itzmx.com:6961/announce`, which is also a IPv6-only tracker, also hosted in Hetzner:

![image](https://github.com/CorralPeltzer/newTrackon/assets/6959494/2e37d58a-b156-4992-87c4-d1322fb68ae4)

Looking at the packets in wireshark, you can observe `udp://tracker3.itzmx.com:6961/announce` (IP is `2a01:4f8:c012:8025::6961`):

![image](https://github.com/CorralPeltzer/newTrackon/assets/6959494/784bcee3-4c0d-45a0-8985-2e464ea1464d)

But no response from `udp://tracker2.itzmx.com:6961/announce` (IP `2a01:4f8:c012:8025::`):

![image](https://github.com/CorralPeltzer/newTrackon/assets/6959494/197180a4-e54d-402f-a6a1-14ed32eefdec)

In your wireshark screenshot, it seems you're actually getting responses from tracker3. I don't think `2a01:4f8:c012:8025::` is a routable IP, it's just the /64 range that Hetzner provides.

**Comment by 1265578519** [comment]
我想我知道原因了，这就和DNS、CDN一样
用户电脑上请求8.8.8.8，但是实际上在谷歌DNS服务器远端节点后面使用其他不同的ip地址用于数据包传输
ipv6 tracker由于和请求相同的ip地址没有回复，回复时服务器使用了其它ip地址，就被qbittorrent与newTrackon判定“超时未响应”
qbittorrent应当使用bep15检测收到的数据包transaction_id是否一致，所以在比特彗星等其它BT客户端上，使用ipv6 udp tracker工作正常，在qbittorrent上不正常
这种现象存在tracker服务器拥有多个ipv6地址上发生，通过了与访问域名目标ip不同的其它ipv6地址回复引起的“超时未响应”

**Comment by 1265578519** [comment]
libtorrent正在修复这个问题，等待更新后qbittorrent也会修复
https://github.com/arvidn/libtorrent/pull/7913
