### ISSUE TITLE
Submitting http tracker into an infinite loop

### ISSUE THREAD

**Issue by lirener** [CorralPeltzer/newTrackon#300]
![QQ截图20241117054140](https://github.com/user-attachments/assets/ad2e6347-d1f5-40a7-87fb-0d0572846377)

Hey, Boss
I want to submit my http tracker: http://ipv4.rer.lol:2710/announce
（我想提交我的http tracker：http://ipv4.rer.lol:2710/announce ）

But I found a problem. By default, using http to submit a website will give priority to using udp.
(但是我发现个问题 默认使用http提交网站会优先使用udp)

I follow the BEP0034 protocol specification and add a TXT record that will turn my http into https
（我遵从BEP0034协议规范 添加TXT记录他会把我的http变成https）

Can this BUG be fixed in the end?（最后能否修复这个BUG？）

Or tell me how to submit a simple http tracker? For example, what kind of TXT record should be added?
（或者告诉我 想要简单的提交http tracker应该怎么做？比如添加什么方式的TXT记录）

I also observed that the same old brand tracker has this problem and it has existed for a long time.
（我还观察到相同老牌子tracker有这样的问题 并且该问题存在许久）
![8{@J@3{L{DBP0T{)TG`BL)X](https://github.com/user-attachments/assets/7928bf88-f152-48f2-802f-361e2cabf1b5)

**Comment by CorralPeltzer** [comment]
Hi! Thanks for reporting the issue, should be fixed now.
