### ISSUE TITLE
Add the ability to separately add and track trackers by different protocols

### ISSUE THREAD

**Issue by stalkerok** [CorralPeltzer/newTrackon#309]
Right now it is impossible to know if a tracker is running a different protocol or not, it has to be done manually for each tracker.

**Comment by CorralPeltzer** [comment]
newTrackon is opinionated on which protocol should be used, and only tries the best one available. I don't see the usecase for this. Closing as out of scope.

**Comment by stalkerok** [comment]
So newTrackon thinks the best protocol is the one the tracker doesn't work on? https://github.com/CorralPeltzer/newTrackon/issues/307
