### ISSUE TITLE
Sugerencia de boton

### ISSUE THREAD

**Issue by OscarReyesLeon** [CorralPeltzer/newTrackon#39]
Mi sugerencia es que el boton "Copy xx Trackers to clipboard" sea colocado en la pagina principal. :D

**Comment by CorralPeltzer** [comment]
Hola Óscar! Aunque es una buena idea, creo que es mejor diferenciar bien las secciones de la web. Si el usuario quiere copiar una lista de trackers, va a `/list` o a `/api/*`. Si quiere obtener información más avanzada sobre trackers individuales, va a la página principal. Creo que añadir el botón de copiar los trackers en la página principal haría que la sección `/list` perdiera el sentido. La sección `/list` es la página más visitada de todo NewTrackon y creo que obligar al usuario que simplemente quiere copiar una lista de trackers estables a cargar la página principal es innecesario y confundiría al usuario básico. De toda formas, te agradezco mucho la idea.

En los próximos _issues_ que abras, si te es posible, apreciaría que usaras inglés para no desalentar a los no hispanohablantes a participar.
