### ISSUE TITLE
Security/Privacy Improvement Idea

### ISSUE THREAD

**Issue by zero77** [CorralPeltzer/newTrackon#4]
Can you add support for SSL/TLS checking, for example, when new trackers are added can you check if they support SSL/TLS and also check existing trackers every so often.

Because of services like letsencrypt.org website admins are implementing SSL/TLS.

Thanks

**Comment by CorralPeltzer** [comment]
Hey! Sorry for the delay. As you can see in the [submitted](https://newtrackon.com/submitted) section, any tracker submitted is tried with UDP, HTTPS and HTTP in that order, and the first that succeeds is the one that gets added. It is the logical order of preference because UDP is the best performing and the preferred one, and HTTPS is obviously better than HTTP.

However, checking periodically if trackers have a different (or just better) protocol available would require another IP in the setup, or modifying the uptime measurement system, because the program has to respect the update interval.

Owners of trackers can always contact me to change the URL or protocol of theirs in the list.

**Comment by zero77** [comment]
Yes sorry, I should have had a better look at the submitted logs first.
If both https and http are found is https added to the list over http, if not can you implement this if not can you implement this. 

Also, for SSL/TLS support testing of pre-existing UDP and HTTP trackers, could this not be done alongside the current status checks, but maybe once a week.

This is an excellent service and idea but, I don’t know how well-known it is within the torrenting community especially by tracker and torrent site admin is. 
Though I think interviews/articles on websites like torrent freak could help to build awareness.

**Comment by CorralPeltzer** [comment]
Yes, if HTTPS works, the tracker is added with an HTTPS URL, and HTTP is not even tried.

I just realized your petition is already in the [TODO list](https://github.com/CorralPeltzer/newTrackon/blob/master/TODO.txt), so I will keep this issue opened until is implemented, I probably won't have much time to do it until August.

The site is not really popular; according to Cloudflare, it receives about 400 unique daily visitors including the API, but probably a quarter of them are not human. It was already [featured in TorrentFreak](https://torrentfreak.com/newtrackon-tracks-torrent-trackers-170108/) 3 months ago, but when you search for "bittorrent trackers list" in search engines, you only get lots of ultra optimized SEO sites that basically are there to make ad money, and I suppose they are really lucrative. Therefore, the only way to find [newtrackon.com](https://newtrackon.com/) is to search specifically for it. I cannot really compete with those search engine optimized sites, (newTrackon is not mobile-friendly ye, doesn't have a comments system, is relatively new...) so I am fine with the site being found by recommendation in forums and other places. So if you like the project, just tell your friends about it :)

**Comment by zero77** [comment]
Excellent thank you although, I couldn’t see it in there, at least nothing about checking if encryption for udp trackers are supported.

Also, the reason I mentioned site popularity is that I don’t think admins are going to update trackers as they don’t know about it.

Yes, free word of mouth advertising within the  torrenting community is probably the best and most efficient way to go.

Maybe by asking as many torrent client and torrent related developers like Duckie TV, Radarr etcetera to build in support for your service as possible. Either by automatically submitting new trackers or automatically adding trackers to your service.

**Comment by CorralPeltzer** [comment]
I'm not sure what you mean with UDP encryption, but I am not aware of such thing in the BitTorrent protocol.

I'm not familiar with the two projects you mentioned, but I'll take a look and propose using the newTrackon API to set their open trackers. Thanks for the heads up!

**Comment by zero77** [comment]
Thanks, they were just examples although I can contact them, if you contact torrent clients like µTorrent, qBittorrent etcetera.

I was just mean encryption support for udp trackers but if this is not currently supported don’t worry.
