### ISSUE TITLE
[Request] Import From Other Tracker Lists

### ISSUE THREAD

**Issue by zero77** [CorralPeltzer/newTrackon#44]
Can you please import trackers from these lists because they have other trackers that are updated regularly.

https://github.com/ngosang/trackerslist 
https://torrents.me/tracker-list/

Also, there seem to be lots of other good lists on git hub and pastbin, it may be worth scraping them.

Thanks

**Comment by CorralPeltzer** [comment]
Hi! https://github.com/ngosang/trackerslist is scraped every day and its trackers submitted to newTrackon, you can see the code [here](https://github.com/CorralPeltzer/newTrackon/blob/master/trackerlist_project.py).

About https://torrents.me/tracker-list/, I'm pretty sure they just scrape my API to create their list. You will see their trackers are almost the same ones, and in the same order as https://newtrackon.com/. This has been going on for several months, and while it is quite unpolite to not mention or link newTrackon, the license allows them. As long as they don't put adds, I'm fine with it.

**Comment by zero77** [comment]
O, I missed that python script.
So, any worth wile lists should be added there for scraping.

**Comment by CorralPeltzer** [comment]
Yes, any dynamic list should be scraped from there.

**Comment by zero77** [comment]
@CorralPeltzer 
Have you considered scraping torrent sites, to find the latest trackers being used but, specifically for the newly uploaded torrents and then under the trackers part of each torrent.

**Comment by CorralPeltzer** [comment]
@zero77 I try to keep this project more community oriented so that new trackers should ideally be submitted by people, but yes, as long as it is fairly simple and doesn't require too many requests, I'm open to scrape some torrent sites. Do you have any proposal?

**Comment by zero77** [comment]
@CorralPeltzer 
Do you mean what sites do I suggest to scrape for trackers?

**Comment by CorralPeltzer** [comment]
Yes, exactly

**Comment by zero77** [comment]
@CorralPeltzer 
Sorry for the late response, here are some of the sites I can suggest although there are others.

Each torrent upload often uses different trackers, on this site.
audiobookbay.nl

These sites have new trackers but less often, a lot of torrents use the same.
 1337x.to bt-scene.cc isohunt2.net limetorrents.io torrentdownloads.me zooqle.com

**Comment by CorralPeltzer** [comment]
Those are piracy related sites, and I don't think there's much value on creating scraping scripts since most of the torrents use the same trackers. Feel free to submit a Pull Request if you implement any scraping.
