### ISSUE TITLE
http://opentracker.xyz:80/announce  and  https://opentracker.xyz:443/announce   ???

### ISSUE THREAD

**Issue by f4nff** [CorralPeltzer/newTrackon#51]
http://opentracker.xyz:80/announce  and  https://opentracker.xyz:443/announce  

Cannot be added to the list at the same time, only one of them can be added。

**Comment by f4nff** [comment]
Some old clients don't support tls, only http,
The same domain name can open http+https, but only one can be added.

**Comment by CorralPeltzer** [comment]
This behaviour is explained in the [submitted](https://newtrackon.com/submitted) section. newTrackon only accepts unique trackers, and for a tracker to be unique, it needs to have a unique hostname and resolve to an IP that is not already in the list. Also, when a new tracker is added, all possible protocols are tried in a specific order, http being the last one. If you have a client that doesn't support https trackers, you should really update it.
