### ISSUE TITLE
Tracker scraping thread hangs forever

### ISSUE THREAD

**Issue by f4nff** [CorralPeltzer/newTrackon#59]
![image](https://user-images.githubusercontent.com/19538878/48175412-e7255700-e346-11e8-9ae0-892353893c11.png)

**Comment by CorralPeltzer** [comment]
DNS problems seem to be able to hang the thread that probes existing trackers. Keeping this issue open to track network error handling improvements.

**Comment by f4nff** [comment]
![image](https://user-images.githubusercontent.com/19538878/53992762-9ee93a80-4168-11e9-85d9-2bd634bc63a0.png)
bug!
