### ISSUE TITLE
Run 'python3 server.py' couldn't connect to server.

### ISSUE THREAD

**Issue by water5** [CorralPeltzer/newTrackon#66]

**Comment by water5** [comment]
When run 'python3 server.py' appear these message:
---------------------------------
python3 server.py

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    14  100    14    0     0     22      0 --:--:-- --:--:-- --:--:--    22
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Couldn't connect to server
Traceback (most recent call last):
  File "server.py", line 11, in <module>
    import trackon
  File "/user1/newTrackon/trackon.py", line 10, in <module>
    from tracker import Tracker
  File "/user1/newTrackon/tracker.py", line 4, in <module>
    import scraper
  File "/user1/newTrackon/scraper.py", line 15, in <module>
    subprocess.check_output(['curl', '-6', 'https://icanhazip.com/']).decode('utf-8').strip()]
  File "/usr/lib64/python3.7/subprocess.py", line 395, in check_output
    **kwargs).stdout
  File "/usr/lib64/python3.7/subprocess.py", line 487, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['curl', '-6', 'https://icanhazip.com/']' returned non-zero exit status 7.
--------------------------------------------------------------

How to solve it ?
Thanks.

**Comment by CorralPeltzer** [comment]
This is most probably because the computer where you are trying to run it doesn't have IPv6 network connectivity. To check it, visit http://ipv6-test.com/.

As explained in the README, for newTrackon to run, you need both IPv4 and IPv6 connectivity.
