### ISSUE TITLE
Disabling IPv6 only trackers by default in list

### ISSUE THREAD

**Issue by miyurusankalpa** [CorralPeltzer/newTrackon#79]
Regarding the commit f7e0990e0ac2e7e40d6a21de228ae5120103363f, Can I know the reasoning behind this?

I operate one of the IPv6 only trackers and what I hope is to connect users to IPv6 swarm, when ISP enables IPv6. This configuration does not encourage this.

The reason for not dual stacking is because some BitTorrent clients connects to IPv4 address by default.

**Comment by CorralPeltzer** [comment]
The _list_ section is meant to provide an easy to use list of trackers that will work for most of people. By any metric available, most people don't have IPv6 access ([1](https://www.google.com/intl/en/ipv6/statistics.html), [2](https://www.akamai.com/us/en/resources/our-thinking/state-of-the-internet-report/state-of-the-internet-ipv6-adoption-visualization.jsp)) so those trackers just won't work for them. People that just copy and paste the list and don't know what is IPv6, will just see that the list provides trackers that don't work. People with access to IPv6 can just click the button. When IPv6 adoption goes above 50%, I'll change the default behaviour.

Maybe you can try requesting that BitTorrent clients change that default behaviour.

**Comment by miyurusankalpa** [comment]
EDIT: just realised, newtrackon shows it by default now. sorry.

https://www.google.com/intl/en/ipv6/statistics.html
