### ISSUE TITLE
Add CORS headers to API responses

### ISSUE THREAD

**Issue by nixxquality** [CorralPeltzer/newTrackon#8]
I tried to make a Javascript tool that uses your API, but since your server doesn't send CORS headers, my browser's security feature kicks in and disallows it.
What is CORS? https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS

Basically, add `Access-Control-Allow-Origin: *` as a header to API responses and it should be fine.

**Comment by CorralPeltzer** [comment]
Thanks for the heads up! Changes are live on the server, it should work. Keep in mind that the site is behind CloudFlare, and it can mess up with strange User-Agents.

Also, if you are gonna do more than a few thousand queries a day, I would appreciate a previous notice to provision the server accordingly.

**Comment by nixxquality** [comment]
Sorry for the late response.
Just took a look at the diff and you misspelled the header as *Acess*.

As for amount of queries, it shouldn't be a problem. It's mostly a personal tool.

**Comment by CorralPeltzer** [comment]
Sorry for the stupid typo, fixing it

**Comment by CorralPeltzer** [comment]
And live on the server
