### ISSUE TITLE
Button for re-check the specified tracker.

### ISSUE THREAD

**Issue by username1565** [CorralPeltzer/newTrackon#84]
Can you just add the button to re-check specified tracker.
For example. Tracker is not responding.
But now this is online. And last check was been 3 hours ago.
Found the specified tracker, press the button, run the check for this tracker, and if this online, this is green and immediately contains in the list of active trackers.

I already see the one button for each tracker, but this just show additional info about it.

Best regards.

**Comment by CorralPeltzer** [comment]
newTrackon respects the update interval reported by trackers, but when a tracker reaches 0% uptime, the interval is set at 3 hours because of the low probability the check will succeed. If a tracker with 0% uptime is back working, newTrackon will update it in 3h or less, and then the update interval will be set again at what the tracker reports.

I don't see much value in adding a manual checking button, which could also open it to abuse.

**Comment by username1565** [comment]
Hm... I don't see any abuse in this option and ability, but maybe, you are right.
Just I'm, as owner of one tracker, see the usability of this option,
and I decided to write for you this "Feature request",
just because I wanted to check my tracker,
using your internal tracker-checker,
but 3 hours is long time to keep the tracker online, just for test.
I see here: https://ping.eu/port-chk/
the port have the status "**open**",
but I cann't check the tracker, by full URL,
and this seems like not responding, and not online.
So I just wanted to check my tracker, and if this working, to see this green,
and added my tracker to another active trackers in that list,
but if this will be offline, then it must be red and inactive,
and not contains in the list of active trackers.

Maybe, you can think about the compromise between usability and safety,
and do this, and add this ability, just for fun,
but if you see some abuse in this option,
I think, will be better to add manually-checked trackers in the end of list,
to prevent and don't let the spam in this list,
with fake and temporary-active trackers.

Have a nice day.

**Comment by CorralPeltzer** [comment]
I understand your use case, but I don't think [newtrackon.com](https://newtrackon.com/) should be used for testing a tracker you own.

For that, I think you have 2 better options:
1. Use a BitTorrent client, like qBittorrent, and force reannounce of a random torrent to your tracker to see if it works.
2. Run newTrackon locally by following the instructions in the [README](https://github.com/CorralPeltzer/newTrackon/blob/master/README.md). This way you can just remove the tracker from the database and submit it again.
